#aws
cloud:
 aws:
  stack:
   auto: false
  region: 
   static: ap-northeast-1
  credentials:
   accessKey: 
   secretKey: 

#mybatis
mybatis:
 type-aliases-package: com.example.model
 mapper-locations: classpath*:/mapper/MYSQL/*.xml

#spring  
spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://aws-and-infra-web.cj8iqiy84gcp.ap-northeast-1.rds.amazonaws.com:3306/sample
  username: db_master
  password: password
  